//auth action type
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';
export const SET_USER = 'SET_USER'


//User/Company Action type
export const ADD_COMPANY_LIST = 'ADD_COMPANY_LIST';
export const ADD_EXCEL_DATA_TO_COMPANY_LIST = 'ADD_EXCEL_DATA_TO_COMPANY_LIST';
export const ADD_COMPANY_TO_LIST = 'ADD_COMPANY_TO_LIST';
export const DELETE_COMPANY_TO_LIST = 'DELETE_COMPANY_TO_LIST';
export const UPDATE_COMPANY_TO_LIST = 'UPDATE_COMPANY_TO_LIST'
export const SHOW_COMPANY_FORM = 'SHOW_COMPANY_FORM';
export const ADD_CURRENT_COMPANY_DATA = 'ADD_CURRENT_COMPANY_DATA';